//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessService {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLMAINResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLMAINResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccessService.SQLMAINResources", typeof(SQLMAINResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ABSznh123 的本地化字符串。
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;SELECT email FROM donate ORDER BY money DESC; 的本地化字符串。
        /// </summary>
        internal static string GETDONATEEMAIL {
            get {
                return ResourceManager.GetString("GETDONATEEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;SELECT id,money FROM donate ORDER BY money DESC; 的本地化字符串。
        /// </summary>
        internal static string GETDONATEIDANDMONEY {
            get {
                return ResourceManager.GetString("GETDONATEIDANDMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano ;INSERT INTO user(NickName,Password,JoinTime,Email) VALUES(&apos;$&apos;,&apos;$&apos;,&apos;$&apos;,&apos;$&apos;); 的本地化字符串。
        /// </summary>
        internal static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;INSERT INTO forgetUser VALUES($,&apos;$&apos;,&apos;$&apos;,&apos;$&apos;) 的本地化字符串。
        /// </summary>
        internal static string INSERTFORGET {
            get {
                return ResourceManager.GetString("INSERTFORGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT * FROM notice ORDER BY notice DESC LIMIT 1 的本地化字符串。
        /// </summary>
        internal static string NOTICE {
            get {
                return ResourceManager.GetString("NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano; SELECT COUNT(*) FROM user WHERE Email=&apos;$&apos;; 的本地化字符串。
        /// </summary>
        internal static string SELECTEMAIL {
            get {
                return ResourceManager.GetString("SELECTEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano; SELECT Id FROM user WHERE Email=&apos;$&apos;; 的本地化字符串。
        /// </summary>
        internal static string SELECTID {
            get {
                return ResourceManager.GetString("SELECTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano; SELECT JoinTime FROM user WHERE Id=$; 的本地化字符串。
        /// </summary>
        internal static string SELECTLOGONTIME {
            get {
                return ResourceManager.GetString("SELECTLOGONTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano; SELECT NickName FROM user WHERE Id = $ AND Password = &apos;$&apos; ; 的本地化字符串。
        /// </summary>
        internal static string SELECTNickName {
            get {
                return ResourceManager.GetString("SELECTNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 server=adminznh.ren;port=3306;user id=user;password=ABSuser123;database=Piano; 的本地化字符串。
        /// </summary>
        internal static string SQLINFO {
            get {
                return ResourceManager.GetString("SQLINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;UPDATE user SET Password=&apos;$&apos; WHERE Id=$ OR Email=&apos;$&apos; OR NickName=&apos;$&apos;; 的本地化字符串。
        /// </summary>
        internal static string UPDATEPWD {
            get {
                return ResourceManager.GetString("UPDATEPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;SELECT * FROM user WHERE Id=$ OR Email=&apos;$&apos;; 的本地化字符串。
        /// </summary>
        internal static string VERIDANDEMAIL {
            get {
                return ResourceManager.GetString("VERIDANDEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USE Piano;SELECT * FROM versions ORDER BY versions DESC LIMIT 1; 的本地化字符串。
        /// </summary>
        internal static string VERSIONS {
            get {
                return ResourceManager.GetString("VERSIONS", resourceCulture);
            }
        }
    }
}
